---

development:
  adapter: postgresql
  encoding: unicode

test:
  adapter: postgresql
  encoding: unicode

staging:
  adapter: postgresql
  encoding: unicode

production:
  adapter: postgresql
  encoding: unicode
